export const DECIMAL_POINT = ".";

export const COMPUTE_AREA_ACTION_TYPE = "COMPUTE_AREA_PARAMS";
export const COMPUTE_VOLUME_ACTION_TYPE = "COMPUTE_VOLUME_PARAMS";
export const ADD_USER_ACTION_TYPE = "ADD_USER_INFO";
export const DEL_USER_ACTION_TYPE = "DEL_USER_INFO";
export const CEAR_DATA_ACTION_TYPE = "CLEAR_USER_DATA";